### ISSUE TITLE
Could there be options to make code larger?

### ISSUE THREAD

**Issue by singularitti** [adevade/code-zoom#1]
I am curious why only smaller?

**Comment by adevade** [comment]
Yeah, sure! 

I really only made this extension for my own use. I have large code fonts by default, and like to make it small to get an overview.

What would "big" be for you?

---

I guess I could make the small and big font settings configurable.

**Comment by singularitti** [comment]
> What would "big" be for you?

I don't know actually. Can we make it whenever you run `code-zoom.smaller`, it shrinks the font size by 1pt? And reversibly, when you type `code-zoom.larger` everytime, it increases the font size by 1pt. So there is no limit for smaller (except for 0pt) and larger.

**Comment by adevade** [comment]
I published a new version now (0.2.0) that lets you define your own values for `small` and `big` in the settings. Search for `Code Zoom` in the settings pane.

> Can we make it whenever you run code-zoom.smaller, it shrinks the font size by 1pt?

Yeah, I guess that could be added. Nothing that I would use personally though.

If you want to take a stab at a PR though, feel free. ✌️
